import './globals.scss';

import cx from 'classnames';
import type { Metadata } from 'next';
import { Cormorant_Garamond, Poppins } from 'next/font/google';

import { Background } from '@/components/Background';
import { Navigation } from '@/components/Navigation';

const cormorantGaramond = Cormorant_Garamond({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--font-cormorantGaramond'
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-poppins'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cx(cormorantGaramond.variable, poppins.variable)}>
        <Background />
        <Navigation />
        {children}
      </body>
    </html>
  );
}
